project:
  type: website
  output-dir: docs


website:
  title: "Analisis in situ: Modelos estadísticos basados en aprendizaje automático para predecir enfermedades en cultivos agrícolas usando variables climáticas de productos satelitales"
  navbar:
    search: false
    title: false
    
    #background: '#ffff'
    #foreground: '#e09c6c'
    left:
      - href: index.qmd
        text: Inicio
      - href: instalacion.qmd
        text: Instalación
      - href: descarga.qmd
        text: Descarga 
      - href: Seleccion de variables.qmd
        text: Seleccíon
      - href: Ajuste.qmd
        text: Ajuste
      
      
  page-footer:
    #background: "#c7d78b"
    right:
      - text: "&#169; 2023 Franco Suarez, Juan Manuel Fiore, Cecilia Bruno <span xmlns:cc=\"http://creativecommons.org/ns#\" xmlns:dct=\"http://purl.org/dc/terms/\">licensed under <a href=\"http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">CC BY 4.0<img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\"><img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\"></a></p>"
      
format:
  html:
    theme: Minty
    css: styles.css
    toc: true

lang: es
citations-hover: true

knitr:
  opts_chunk: 
    #collapse: true
    comment: "##"
    results: "hold"

editor: visual

